### ISSUE TITLE
CocoaPods?

### ISSUE THREAD

**Issue by orta** [StrangerApp/STOFMessagesViewController#1]
Hi there, looks like this is more or less an exact duplicate of JSQMessagesViewController - any reasons for having this as a separate pod? You can use `pod "JSQMessagesViewController", :git => "https://github.com/StrangerApp/STOFMessagesViewController.git"` instead to refer to this fork

**Comment by imton** [comment]
yup, sorry but cocoa-pods doesn't allow me to directly specify a dependency from git in a podspec and this will be personally different.

**Comment by jessesquires** [comment]
@imton hm... can you explain a bit more, I'm not sure I understand?

**Comment by jessesquires** [comment]
WhisperSystems maintains a [custom fork](https://github.com/WhisperSystems/JSQMessagesViewController) for [Signal iOS](https://github.com/WhisperSystems/Signal-iOS/blob/master/Podfile).

Is this what you need?

**Comment by imton** [comment]
What I need is to have two different forks of the original of this with customizations. Some complex stuff I am forced to have in the open because private pod spec dependencies are not easy to setup. Sorry

**Comment by orta** [comment]
A custom specs repo is as simple as creating a git repo and adding a file or two, [it's dead easy](https://github.com/artsy/specs) 
You can also define any dependencies inside the Podfile, the Podspec isn't meant to care about where it comes from. 

By adding this to the CP trunk, you're effectively making it harder for others to use the original, and it's not a good experience for others, I'd recommend you push another version with the deprecation flag.

**Comment by jessesquires** [comment]
Ahh, I see. You could setup a spec repo under the StrangerApp organization that just contains this pod. I'd be happy to help set it up. :smile: 

At the very least, I think we should [revert this commit](https://github.com/CocoaPods/Specs/blob/master/Specs/STOFMessagesViewController/7.3.1/STOFMessagesViewController.podspec.json) and re-submit a pod spec that uses StrangerApp's credentials instead of impersonating me. :smile:

RE: reverting — @orta is that even possible, or.. ?

**Comment by orta** [comment]
There is both a `pod trunk delete` and `pod trunk deprecate`  command in the betas, I think deprecate has a known bug server-side, but delete should work. The Specs repo is now effectively read-only WRT being a git repo now.

**Comment by imton** [comment]
@orta @jessesquires guys, thank you, I appreciate your cooperation. I know how to create a private source.  I understand your concerns, time constraints sorry again. Will do it soon.

**Comment by imton** [comment]
@orta @jessesquires feel free to remove this from public source now, thanks
